export enum STORAGE_KEY {
  CURRENT_USER = 'CURRENT_USER',
  CURRENT_EMPLOYEE = 'CURRENT_EMPLOYEE',
  AUTHEN_TOKEN = 'AUTHEN_TOKEN',
  CURRENT_LANGUAGE = 'CURRENT_LANGUAGE',
  APP_SETTING = 'APP_SETTING',
}

export enum STORAGE_TYPE {
  INDEXDB = 'INDEXDB',
  LOCAL_STORAGE = 'AUTHEN_TOKEN',
}
