version: '3'
services:
  fe:
    image: aninfosys.asia:8082/learnhub/fe:1.0
    deploy:
      restart_policy:
        condition: any
      replicas: 1
    networks:
      - ctedu_internal
networks:
  ctedu_internal:
