FROM adview.cxview.ai/lpdev/dsd/dsd-frontend-cache-uat:latest as build


WORKDIR /app
RUN mkdir -p /app/deploy
COPY package.json ./
COPY package-lock.json ./
COPY angular.json ./
COPY tsconfig.json ./
COPY libs ./libs
COPY projects ./projects
COPY assets ./assets

RUN npm run build:prod


FROM nginx
COPY --from=build /app/deploy/web /usr/share/nginx/html
COPY docker/nginx/config/default_uat.conf /etc/nginx/conf.d/default.conf
