/**
 * API Core
 * Group api-core
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AspNetUsersDto {
  createdBy?: string;
  modifiedBy?: string | null;
  createdDate?: string;
  modifiedDate?: string | null;
  id?: string | null;
  tenantId?: string | null;
  tenantName?: string | null;
  userName?: string | null;
  normalizedUserName?: string | null;
  email?: string | null;
  normalizedEmail?: string | null;
  emailConfirmed?: boolean;
  password?: string | null;
  passwordHash?: string | null;
  phoneNumber?: string | null;
  phoneNumberConfirmed?: boolean;
  twoFactorEnabled?: boolean;
  lockoutEnd?: string | null;
  lockoutEnabled?: boolean;
  accessFailedCount?: number;
  fullName?: string | null;
  employeeId?: string | null;
  employeeCode?: string | null;
  usedState?: number;
  description?: string | null;
  avatar?: string | null;
  lastChangePassword?: string | null;
  lastDateLogin?: string | null;
}
