/**
 * Dsd API
 * DSD Information
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Playlist } from './playlist';

export interface BaseOutputPlaylist {
  errors?: Array<string>;
  message?: string;
  currentPage?: number;
  pageSize?: number;
  totalPages?: number;
  status?: BaseOutputPlaylist.StatusEnum;
  data?: Playlist;
}
export namespace BaseOutputPlaylist {
  export type StatusEnum = 'SUCCESS' | 'FAILED';
  export const StatusEnum = {
    Success: 'SUCCESS' as StatusEnum,
    Failed: 'FAILED' as StatusEnum,
  };
}
