/**
 * Dsd API
 * DSD Information
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResponseStatus } from './responseStatus';
import { DeviceUpdateStatus } from './deviceUpdateStatus';

export interface BaseOutputDeviceUpdateStatus {
  errors?: Array<string>;
  message?: string;
  currentPage?: number;
  pageSize?: number;
  totalPages?: number;
  total?: number;
  status?: ResponseStatus;
  data?: DeviceUpdateStatus;
}
export namespace BaseOutputDeviceUpdateStatus {}
