/**
 * Dsd API
 * DSD Information
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DeviceGroup } from './deviceGroup';


export interface BaseOutputDeviceGroup { 
    errors?: Array<string>;
    message?: string;
    currentPage?: number;
    pageSize?: number;
    totalPages?: number;
    data?: DeviceGroup;
}

