/**
 * Dsd API
 * DSD Information
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DsdFile } from './dsdFile';
import { Status } from './status';

export interface Category {
  id?: number;
  name?: string;
  description?: string;
  status?: Status;
  files?: DsdFile[];
}
export namespace Category {}
