/**
 * Dsd API
 * DSD Information
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Playlist } from './playlist';

export interface DashBoardResponse {
  totalOfflineDevices?: number;
  totalOnlineDevices?: number;
  totalDeviceGroups?: number;
  totalPlaylists?: number;
  lastPlaylist?: Playlist;
}
