/**
 * Dsd API
 * DSD Information
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DeviceUpdateStatusRequest { 
    license?: string;
    code?: string;
    status?: DeviceUpdateStatusRequest.StatusEnum;
}
export namespace DeviceUpdateStatusRequest {
    export type StatusEnum = 'ONLINE' | 'OFFLINE' | 'UNDEFINED';
    export const StatusEnum = {
        Online: 'ONLINE' as StatusEnum,
        Offline: 'OFFLINE' as StatusEnum,
        Undefined: 'UNDEFINED' as StatusEnum
    };
}


