/**
 * Dsd API
 * DSD Information
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Status } from './status';
import { Playlist } from './playlist';
import { User } from './user';
import { Device } from './device';

export interface DeviceGroup {
  id?: number;
  name?: string;
  description?: string;
  status?: Status;
  devices?: Array<Device>;
  user?: User;
  playlist?: Playlist;
}
export namespace DeviceGroup {}
