/**
 * Dsd API
 * DSD Information
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Device } from './device';


export interface DeviceLog { 
    id?: number;
    date?: string;
    device?: Device;
}

