/**
 * Dsd API
 * DSD Information
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { Device } from './device';


export interface DeviceGroup { 
    id?: number;
    name?: string;
    description?: string;
    devices?: Array<Device>;
    user?: User;
}

