/**
 * Dsd API
 * DSD Information
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DeviceStatus } from './deviceStatus';

export interface DeviceUpdateStatusRequest {
  license?: string;
  code?: string;
  status?: DeviceStatus;
}
export namespace DeviceUpdateStatusRequest {}
