/**
 * Dsd API
 * DSD Information
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Playlist } from './playlist';
import { User } from './user';


export interface DsdFile { 
    id?: number;
    name?: string;
    fileType?: string;
    path?: string;
    playlist?: Playlist;
    user?: User;
}

