/**
 * Dsd API
 * DSD Information
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Status } from './status';
import { Playlist } from './playlist';
import { Category } from './category';
import { User } from './user';

export interface DsdFile {
  id?: number;
  name?: string;
  fileType?: string;
  path?: string;
  createDate?: string;
  status?: Status;
  playlist?: Playlist;
  user?: User;
  category?: Category;
}
export namespace DsdFile {}
