/**
 * Dsd API
 * DSD Information
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlaylistStatus } from './playlistStatus';
import { User } from './user';
import { DsdFile } from './dsdFile';
import { DeviceGroup } from './deviceGroup';

export interface Playlist {
  id?: number;
  name?: string;
  description?: string;
  startTime?: string;
  endTime?: string;
  isLoop?: boolean;
  status?: PlaylistStatus;
  files?: Array<DsdFile>;
  deviceGroups?: Array<DeviceGroup>;
  user?: User;
}
export namespace Playlist {}
