/**
 * Hub.Auth.Api
 * Group api-core
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseUserInfo { 
    tenantId?: string | null;
    tenantType?: string | null;
    userId?: string | null;
    employeeId?: string | null;
    userName?: string | null;
    email?: string | null;
    phoneNumber?: string | null;
    displayName?: string | null;
    readonly gender?: string | null;
    readonly birthday?: string | null;
    avatar?: string | null;
    isVerified?: boolean;
}

