/**
 * Dsd API
 * DSD Information
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Role { 
    id?: number;
    name?: string;
    type?: Role.TypeEnum;
}
export namespace Role {
    export type TypeEnum = 'ADMIN' | 'USER' | 'UNDEFINED';
    export const TypeEnum = {
        Admin: 'ADMIN' as TypeEnum,
        User: 'USER' as TypeEnum,
        Undefined: 'UNDEFINED' as TypeEnum
    };
}


