/**
 * Dsd API
 * DSD Information
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Playlist } from './playlist';


export interface Schedule { 
    id?: number;
    name?: string;
    description?: string;
    days?: Set<number>;
    playlists?: Array<Playlist>;
}

