/**
 * Hub.Auth.Api
 * Group api-core
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TokenReturn } from './tokenReturn';
import { ErrorResponse } from './errorResponse';


export interface TokenReturnCustomApiObjResponse {
    isError?: boolean;
    statusCode?: number;
    message?: string | null;
    errors?: Array<ErrorResponse> | null;
    result?: TokenReturn;
    last_page?: number;
    current_page?: number;
}

