/**
 * Hub.Auth.Api
 * Group api-core
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface TokenReturn {
  access_token?: string | null;
  expires_in?: number;
  message?: string | null;
  userName?: string | null;
  displayName?: string | null;
  userid?: string | null;
  employeeId?: string | null;
  tenantId?: string | null;
  tenantName?: string | null;
  tenantType?: string | null;
  avatar?: string | null;
  isVerified?: boolean;
}
