/**
 * Dsd API
 * DSD Information
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { License } from './license';

export interface User {
  id?: number;
  userName?: string;
  email?: string;
  password?: string;
  phone?: string;
  firstName?: string;
  lastName?: string;
  roles?: User;
  license?: License;
}
