/**
 * Dsd API
 * DSD Information
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { License } from './license';
import {Role} from "./role";


export interface User {
    id?: number;
    userName?: string;
    email?: string;
    password?: string;
    phone?: string;
    firstName?: string;
    lastName?: string;
    // roles?: Role;
    license?: License;
}

