/**
 * Dsd API
 * DSD Information
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { DeviceGroup } from './deviceGroup';
import { DeviceStatus } from './deviceStatus';
import { DeviceLog } from './deviceLog';

export interface Device {
  id?: number;
  code?: string;
  name?: string;
  information?: string;
  description?: string;
  status?: DeviceStatus;
  user?: User;
  deviceGroup?: DeviceGroup;
  deviceLogs?: Array<DeviceLog>;
}
export namespace Device {
  export type StatusEnum = 'ONLINE' | 'OFFLINE' | 'UNDEFINED';
  export const StatusEnum = {
    Online: 'ONLINE' as StatusEnum,
    Offline: 'OFFLINE' as StatusEnum,
    Undefined: 'UNDEFINED' as StatusEnum,
  };
}
