/**
 * Dsd API
 * DSD Information
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Device } from './device';
import { DeviceStatus } from './deviceStatus';


export interface DeviceLog { 
    id?: number;
    date?: string;
    status?: DeviceStatus;
    device?: Device;
}
export namespace DeviceLog {
}


