/**
 * Dsd API
 * DSD Information
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface License { 
    id?: number;
    code?: string;
    token?: string;
    publicKey?: string;
    privateKey?: License;
    activationDate?: string;
    expirationDate?: string;
    description?: string;
}

